[book]
authors = ["Stephen Doyle"]
language = "en"
src = "src"
title = "Programming Accelerators"

[output.html]
mathjax-support = true
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
